version: '1'
services:
  frontend:
    container_name: frontend
    working_dir: /usr/src/app
    image: node:18.16-slim

    environment:
      - REACT_APP_API_URL=https://google.com/api/v1

    volumes:
      - ./:/usr/src/app

    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - 5173:5173
