version: '1'
services:
  web-ui:
    image: node:18.16-slim

    environment:
      - REACT_APP_API_URL=https://google.com/api/v1

    volumes:
      - ./:/usr/share/nginx/html

    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - 8000:80
